Urls-Django-master/about/urls.py
from django.urls import path,re_path
from . import views
from django.conf.urls import include


app_name = 'about'
urlpatterns = [
       path('', views.index, name='index'),
]

Urls-Django-master/akucoba/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from . import views
from django.http import HttpResponse
 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('about/', include('about.urls', namespace='about')),
    path('form/',  views.form, name='form'),
    path('', views.index, name='index'),
    re_path(r'^articles/(?P<year>[0-9]{4})/$', views.articles),
]

Urls-Django-master/blogs/urls.py
from django.urls import path,re_path
from . import views


app_name = 'blogs'
urlpatterns = [
    path('', views.index, name='index'),
    path('recent/', views.recent, name='recent'),
    path('post/', views.recent,name='post'),
]

Urls-Django-master/about/models.py
from django.db import models

# Create your models here.

Urls-Django-master/akucoba/models.py
from pyexpat import model
from turtle import title
from unittest.util import _MAX_LENGTH
from django.db import models

class Post(models.Model):

    title = models.CharField(max_length=255)
    body = models.TextField()

    def __str__(self) -> str:
        return "{}".format(self.title)

Urls-Django-master/blogs/models.py
from django.db import models

# Create your models here.

Urls-Django-master/akucoba/forms.py
from django import forms;

class pukulpedo(forms.Form):
    namac = forms.CharField()
    alamatc = forms.CharField()

Urls-Django-master/about/views.py
from django.shortcuts import render

def index(request):
    return render (request,'about.html');

def recent(request):
    return render (request,'about.html');

Urls-Django-master/akucoba/views.py
from multiprocessing import context
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post
from . import forms


def index(request):

    db = Post.objects.all()
    context = {
        'title':'picah',
        'post': db
    }
    return render (request,'index.html', context);

def form(request):
    classform =  forms.pukulpedo()

    context = {
        'title': 'sb',
        'classform': classform
    }

    if request.method == 'POST':
        context['nama'] = request.POST['nama']
        context['alamat'] = request.POST['alamat']
        context['namac'] = request.POST['namac']
        context['alamatc'] = request.POST['alamatc']
    else:
        # return render(request, 'form.html')
        print("ini get")
    return render(request, 'form.html', context,)
    

def articles(request,year):
    year=year 
    str=year
    return HttpResponse(year)



# def index(request):
#     # return HttpResponse(" <h1> Hello, world. You're at the polls index.</h1>")
#     return render(request,'template/index.html')

Urls-Django-master/blogs/views.py
from django.shortcuts import render

def index(request):
    return render (request,'blogs.html');

def recent(request):
    return render (request,'blogs.html');

Urls-Django-master/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content-1 %}
    
    {% for v in post %}
    <h1>{{v.title}}</h1>
    {% endfor %}
{% endblock content-1 %}

<hr>
<h1>ini adalah about</h1>

<ul>
    <li ><a href="{% url 'index' %}">home</a></li>
    <li ><a href="{% url 'blogs:index' %}">blogs</a></li>
    <li ><a href="{% url 'about:index' %}">about</a></li>
    <li ><a href="{% url 'form' %}">form</a></li>
</ul>
</body>
</html>

Urls-Django-master/templates/blogs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content-1 %}
    
    {% for v in post %}
    <h1>{{v.title}}</h1>
    {% endfor %}
{% endblock content-1 %}

<hr>

<h1>ini adalah blogs</h1>

<ul>
    <li ><a href="{% url 'index' %}">home</a></li>
    <li ><a href="{% url 'blogs:index' %}">blogs</a></li>
    <li ><a href="{% url 'about:index' %}">about</a></li>
    <li ><a href="{% url 'form' %}">form</a></li>
</ul>
</body>
</html>

Urls-Django-master/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content-1 %}
    
    {% for v in post %}
    <h1>{{v.title}}</h1>
    {% endfor %}
{% endblock content-1 %}

<hr>

<h1>ini adalah form</h1>
<form method="POST">
{% csrf_token %}
<table>{{classform.as_table}}</table>
<label for="">isi nama</label>
<input type="text" id="nama" name="nama">
<label for="">isi alamatmu</label>
<input type="text" id="alamat" name="alamat">
<button type="submit">kirim</button>
</form>
<h2>ini namamu {{nama}} atao {{namac}}</h2>
<h2>alamatmu {{alamat}}atao {{alamatc}}</h2>

<ul>
    <li ><a href="{% url 'index' %}">home</a></li>
    <li ><a href="{% url 'blogs:index' %}">blogs</a></li>
    <li ><a href="{% url 'about:index' %}">about</a></li>
    <li ><a href="{% url 'form' %}">form</a></li>
</ul>
</body>
</html>

Urls-Django-master/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content-1 %}
    
    {% for v in post %}
    <h1>{{v.title}}</h1>
    {% endfor %}
{% endblock content-1 %}

<hr>

<ul>
    <li ><a href="{% url 'index' %}">home</a></li>
    <li ><a href="{% url 'blogs:index' %}">blogs</a></li>
    <li ><a href="{% url 'about:index' %}">about</a></li>
    <li ><a href="{% url 'form' %}">form</a></li>
</ul>
</body>
</html>